query ActivityScreenData(
  $postsFirst: Int
  $postsAfter: String
  $storiesFirst: Int
  $storiesAfter: String
) {
  ...ActivityPosts
  ...ActivityStories
}

query ActivityPosts($postsFirst: Int, $postsAfter: String) {
  ...ActivityPosts
}

query ActivityStories($storiesFirst: Int, $storiesAfter: String) {
  ...ActivityStories
}

fragment ActivityPosts on Query {
  posts(first: $postsFirst, after: $postsAfter) {
    edges {
      node {
        id
        ...PostCard
      }
    }
    pageInfo {
      ...PageInfo
    }
  }
}

fragment ActivityStories on Query {
  stories(first: $storiesFirst, after: $storiesAfter) {
    edges {
      node {
        id
        contentUrl
        user {
          id
          firstProfileImage {
            ...ProfileImage
          }
        }
      }
    }
    pageInfo {
      ...PageInfo
    }
  }
}
