query HomeScreenData(
  $nearbyUsersFirst: Int
  $nearbyUsersAfter: String
  $storiesFirst: Int
  $storiesAfter: String
) {
  ...HomeNearByUsers
  ...HomeStories
}

query HomeNearByUsers($nearbyUsersFirst: Int, $nearbyUsersAfter: String) {
  ...HomeNearByUsers
}

query HomeStories($storiesFirst: Int, $storiesAfter: String) {
  ...HomeStories
}

fragment HomeNearByUsers on Query {
  nearbyUsers(first: $nearbyUsersFirst, after: $nearbyUsersAfter) {
    edges {
      node {
        ...UserCard
      }
      cursor
    }
    pageInfo {
      ...PageInfo
    }
  }
}

fragment HomeStories on Query {
  storyUsers(first: $storiesFirst, after: $storiesAfter) {
    edges {
      node {
        ...StoryUserCircle
      }
    }
    pageInfo {
      ...PageInfo
    }
  }
}
