query GroupQRCodeOwnerInGroupQRCode($id: ID!) {
  user(id: $id) {
    id
    ...ConfirmGroupOwnerInGroupQRCode
  }
}

fragment ConfirmGroupOwnerInGroupQRCode on User {
  id
  nickname
  firstProfileImage {
    ...ProfileImage
  }
}
