query QuestionReplysScreenData($id: Int!) {
  questionReply(id: $id) {
    ...QuestionCard
    replys {
      ...QuestionCard
    }
    questionReply {
      id
      text
    }
    question {
      id
      text
    }
  }
}
