query OneUserStories($id: ID!, $seenCount: Int) {
  user(id: $id) {
    id
    ...StoryUserMetaData
    stories {
      id
      url
      type
      backgroundColors
      thumbnailUrl
      createdAt
      seenList(count: $seenCount) {
        id
        user {
          id
          firstProfileImage {
            ...ProfileImage
          }
        }
      }
    }
  }
}

fragment StoryUserMetaData on User {
  id
  nickname
  firstProfileImage {
    ...ProfileImage
  }
}
