query OneUserStories($id: ID!, $viewersFirst: Int, $storyIdsToDisplay: [Int!]) {
  user(id: $id) {
    id
    ...StoryUserMetaData
    stories(ids: $storyIdsToDisplay) {
      id
      url
      type
      backgroundColors
      thumbnailUrl
      createdAt
      ...ViewersInStories
    }
  }
}

query AfterDeletingStory {
  me {
    ...StoryUserCircle
  }
}

fragment StoryUserMetaData on User {
  id
  nickname
  firstProfileImage {
    ...ProfileImage
  }
}

fragment ViewersInStories on Story {
  seenList(first: $viewersFirst) {
    edges {
      node {
        id
        user {
          id
          firstProfileImage {
            ...ProfileImage
          }
        }
      }
    }
  }
}
