fragment QuestionCard on QuestionEntity {
  ... on QuestionEntity {
    id
    text
    createdAt
    isAnonymity
    user {
      id
      nickname
      firstProfileImage {
        ...ProfileImage
      }
    }
    images {
      url
    }
    replys {
      id
    }
  }
}
