fragment StoryUserCircle on UserEntity {
  id
  nickname
  firstProfileImage {
    ...ProfileImage
  }
  stories {
    id
    url
    backgroundColors
    type
    createdAt
    thumbnailUrl
    seen
  }
}
