query MessageRoomListScreenData {
  ...MessageRoomListScreenData
}

query MessageRoomListFromMySelfScreenData {
  ...MessageRoomListFromMySelf
}

query MessageRoomListFromOtherPartyScreenData {
  ...MessageRoomListFromOtherParty
}

query KeptMessageRoomListScreenData {
  ...KeptMessageRoomList
}

fragment RoomListItemInMessageRoomListScreen on MessageRoom {
  id
  partner {
    id
    nickname
    firstProfileImage {
      ...ProfileImage
    }
    distance
  }
  kept
  lastMessage {
    id
    text
    read
    sender {
      id
    }
    createdAt
  }
  updatedAt
}

fragment MessageRoomListScreenData on Query {
  ...MessageRoomListFromMySelf
  ...MessageRoomListFromOtherParty
  ...KeptMessageRoomList
}

fragment MessageRoomListFromMySelf on Query {
  me {
    id
    messageRoomsFromMySelf {
      ...RoomListItemInMessageRoomListScreen
    }
  }
}

fragment MessageRoomListFromOtherParty on Query {
  me {
    id
    messageRoomsFromOtherParty {
      ...RoomListItemInMessageRoomListScreen
    }
  }
}

fragment KeptMessageRoomList on Query {
  me {
    id
    keptMessageRooms {
      ...RoomListItemInMessageRoomListScreen
    }
  }
}
