query MessageRoomListScreenData {
  ...MessageRoomListScreenData
}

query ExchangingMessageRoomListScreenData {
  ...ExchangingMessageRoomList
}

query NoReplyMessageRoomListScreenData {
  ...NoReplyMessageRoomList
}

fragment RoomListItemInMessageRoomListScreen on MessageRoom {
  id
  partner {
    id
    nickname
    firstProfileImage {
      ...ProfileImage
    }
    distance
  }
  kept
  lastMessage {
    id
    text
    read
    sender {
      id
    }
    createdAt
  }
  updatedAt
}

fragment MessageRoomListScreenData on Query {
  ...ExchangingMessageRoomList
  ...NoReplyMessageRoomList
}

fragment ExchangingMessageRoomList on Query {
  me {
    id
    exchangingMessageRooms {
      ...RoomListItemInMessageRoomListScreen
    }
  }
}

fragment NoReplyMessageRoomList on Query {
  me {
    id
    noReplyMessageRooms {
      ...RoomListItemInMessageRoomListScreen
    }
  }
}
