query MessageRoomListScreenData {
  ...MessageRoomListFromMySelf
  ...MessageRoomListFromOtherParty
}

query MessageRoomListFromMySelfScreenData {
  ...MessageRoomListFromMySelf
}

query MessageRoomListFromOtherPartyScreenData {
  ...MessageRoomListFromOtherParty
}

fragment RoomListItemInMessageRoomListScreen on MessageRoom {
  id
  partner {
    id
    nickname
    firstProfileImage {
      ...ProfileImage
    }
    distance
  }
  messages(first: 1) {
    edges {
      node {
        id
        text
        read
        sender {
          id
        }
        createdAt
      }
    }
  }
}

fragment MessageRoomListFromMySelf on Query {
  me {
    id
    messageRoomsFromMySelf {
      ...RoomListItemInMessageRoomListScreen
      updatedAt
    }
  }
}

fragment MessageRoomListFromOtherParty on Query {
  me {
    id
    messageRoomsFromOtherParty {
      ...RoomListItemInMessageRoomListScreen
      updatedAt
    }
  }
}
