query StoryViewersScreenData(
  $storyId: Int!
  $seenListFirst: Int
  $seenListAfter: String
) {
  story(id: $storyId) {
    id
    seenList(first: $seenListFirst, after: $seenListAfter) {
      edges {
        node {
          id
          user {
            id
            nickname
            firstProfileImage {
              ...ProfileImage
            }
          }
        }
      }
      pageInfo {
        ...PageInfo
      }
    }
  }
}
