query MessageRoomScreenData(
  $id: Int!
  $messagesAfter: String
  $messagesFirst: Int
) {
  messageRoom(id: $id) {
    id
    messages(after: $messagesAfter, first: $messagesFirst) {
      edges {
        node {
          id
          ...MessageBubbleDataInMessageRoom
        }
        cursor
      }
      pageInfo {
        ...PageInfo
      }
    }
    keepingRequest {
      id
    }
    sender {
      id
    }
    ...InputComposerDataInMessageRoomScreen
  }
  me {
    id
    ageVerificationStatus
  }
}

query RoomMessagesInMessageRoomScreen(
  $id: Int!
  $messagesAfter: String
  $messagesFirst: Int
) {
  messageRoom(id: $id) {
    id
    messages(after: $messagesAfter, first: $messagesFirst) {
      edges {
        node {
          id
          ...MessageBubbleDataInMessageRoom
        }
        cursor
      }
      pageInfo {
        ...PageInfo
      }
    }
  }
}

query NicknameAndProfileImageInMessageRoomScreen($id: ID!) {
  user(id: $id) {
    id
    nickname
    firstProfileImage {
      ...ProfileImage
    }
  }
}

fragment MessageBubbleDataInMessageRoom on Message {
  id
  text
  createdAt
  read
  sender {
    id
    firstProfileImage {
      ...ProfileImage
    }
  }
}

fragment InputComposerDataInMessageRoomScreen on MessageRoom {
  id
  kept
  keepingRequest {
    id
    requestUser {
      id
    }
  }
}
