query MyGroupScreenData {
  me {
    id
    group {
      id
      owner {
        id
        nickname
        firstProfileImage {
          ...ProfileImage
        }
      }
      members {
        id
        user {
          id
          ...UserCard
        }
      }
    }
  }
}
