query TimelineScreenData(
  $first: Int
  $after: String
  $input: NarrowingDownInput!
) {
  posts(first: $first, after: $after, input: $input) {
    edges {
      node {
        ...PostCard
      }
      cursor
    }
    pageInfo {
      ...PageInfo
    }
  }
}
