query getMe {
  me {
    id
    nickname
    sex
    initialStatusCompletion
    birthYear
    birthMonth
    birthDay
  }
}

query getInitialStatusCompletion {
  me {
    initialStatusCompletion
  }
}
