query EditProfileScreenData {
  me {
    id
    nickname
    bio
    statusMessage
    height
    profileImages {
      id
      url
    }
    myTags {
      id
      text
    }
    genderOfLoveInterest
  }
}
