fragment ProfileImagesInUserProfile on User {
  profileImages {
    ...ProfileImage
  }
}

query UserProfileScreenData($id: ID!) {
  user(id: $id) {
    id
    nickname
    bio
    ...ProfileImagesInUserProfile
  }
}
